; PlatformIO Project Configuration File

[env:sparkfun_promicro16]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = realtadango/S.Port sensor library for FrSky@^1.0.2

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_speed = 19200
lib_deps = realtadango/S.Port sensor library for FrSky@^1.0.2
build_flags =
    -D F_CPU=16000000L
    -D ARDUINO_AVR_NANO

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168
framework = arduino
monitor_speed = 115200
upload_speed = 19200
lib_deps = realtadango/S.Port sensor library for FrSky@^1.0.2
build_flags =
    -D F_CPU=16000000L
    -D ARDUINO_AVR_NANO




[env:pico]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = realtadango/S.Port sensor library for FrSky@^1.0.2
build_flags =
    -DUSING_PICO
    -I${PROJECT_DIR}/include
